services:
  - docker

script:
  - make stage

after_success:
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make travispushdocker
  - curl -i --form sec=$BINDER_SEC --form file=@bin/nginx --form path=nginx/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@bin/nginx --form filename=nginx-latest-linux-amd64 --form path=nginx/ https://cryo.unixvoid.com/upload
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  - make travisaci
  - make gpgsign
  - curl -i --form sec=$BINDER_SEC --form file=@`ls *.aci` --form path=rkt/nginx/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls *.aci.asc` --form path=rkt/nginx/ https://cryo.unixvoid.com/upload
